-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 11:42:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Base_Projet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Base_Projet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Base_Projet` DEFAULT CHARACTER SET utf8 ;
USE `Base_Projet` ;

-- -----------------------------------------------------
-- Table `Base_Projet`.`Salles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_Projet`.`Salles` (
  `Numéro` INT NOT NULL AUTO_INCREMENT,
  `Batiment` VARCHAR(2) NOT NULL,
  `Etage` INT,
  PRIMARY KEY (`Numéro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Base_Projet`.`Mesure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_Projet`.`Mesure` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CO2` VARCHAR(20) NOT NULL,
  `Temp` VARCHAR(25) NOT NULL,
  `Hum` VARCHAR(45) NOT NULL,
  `Date/Heure` TIMESTAMP NOT NULL,
  `Salles_Numéro` INT NOT NULL,
  PRIMARY KEY (`id`, `Salles_Numéro`),
  INDEX `fk_Mesure_Salles1_idx` (`Salles_Numéro` ASC) VISIBLE,
  CONSTRAINT `fk_Mesure_Salles1`
    FOREIGN KEY (`Salles_Numéro`)
    REFERENCES `Base_Projet`.`Salles` (`Numéro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Base_Projet`.`Capteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_Projet`.`Capteur` (
  `Numéro` INT NOT NULL AUTO_INCREMENT,
  `Version` VARCHAR(45) NULL,
  `Salles_Numéro` INT NOT NULL,
  PRIMARY KEY (`Numéro`, `Salles_Numéro`),
  INDEX `fk_Capteur_Salles_idx` (`Salles_Numéro` ASC) VISIBLE,
  CONSTRAINT `fk_Capteur_Salles`
    FOREIGN KEY (`Salles_Numéro`)
    REFERENCES `Base_Projet`.`Salles` (`Numéro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
